In [105]:
import pandas as pd

In [106]:
df = pd.read_csv(r"C:\Users\Somya Kala\Downloads\customer_shopping_behavior.csv")

In [107]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [109]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [110]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [111]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [112]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [113]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [114]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [115]:
 df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [116]:
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4 ,labels=labels)

In [117]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [118]:
#purchase_frequency_days

frequency_mapping={
    'Fortnightly':14,
     'Weekly':7,   
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
        
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [119]:
df[['frequency_of_purchases','purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [123]:
df = df.drop(columns=["promo_code_used"])

In [124]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-aged,90

In [125]:
pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [126]:
pip install pandas sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (2.0.49)
Requirement already satisfied: pymysql in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: greenlet>=1 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in C:\Users\Somya Kala\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [129]:
import pandas as pd
from sqlalchemy import create_engine, text

# ============================================
# STEP 1 - LOAD YOUR ORIGINAL DATA
# ============================================
df = pd.read_csv(r"C:\Users\Somya Kala\Downloads\customer_shopping_behavior.csv")  # Replace with your actual filename
print("✅ Data Loaded!")
print(f"Shape: {df.shape}")

# ============================================
# STEP 2 - CLEAN COLUMN NAMES
# ============================================
# Lowercase all column names
df.columns = df.columns.str.lower()

# Replace spaces with underscores
df.columns = df.columns.str.replace(' ', '_')

# Rename purchase amount column
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

print("✅ Columns Renamed!")
print(df.columns.tolist())

# ============================================
# STEP 3 - DROP UNWANTED COLUMNS
# ============================================
df = df.drop(columns=["promo_code_used"])

print("✅ Promo Code Column Dropped!")

# ============================================
# STEP 4 - REMOVE NULL VALUES
# ============================================
df = df.dropna(subset=["customer_id"])

print(f"✅ Nulls Removed! Remaining rows: {len(df)}")

# ============================================
# STEP 5 - ADD FREQUENCY MAPPING COLUMN
# ============================================
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

print("✅ Frequency Mapping Done!")
print(df[['frequency_of_purchases', 'purchase_frequency_days']].head())

# ============================================
# STEP 6 - VERIFY DATAFRAME BEFORE PUSHING
# ============================================
print("\n✅ Final Column Names:")
print(df.columns.tolist())
print(f"\n✅ Final Shape: {df.shape}")
print("\n✅ Preview:")
print(df.head())

# ============================================
# STEP 7 - CONNECT TO MYSQL
# ============================================
engine = create_engine("mysql+pymysql://root:13082003@localhost:3306/Customer_behavior")

try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT DATABASE();"))
        print("\n✅ Connected to:", result.fetchone())
except Exception as e:
    print("❌ Connection Error:", e)

# ============================================
# STEP 8 - DROP OLD TABLE & PUSH TO MYSQL
# ============================================
try:
    # Drop old table
    with engine.connect() as conn:
        conn.execute(text("DROP TABLE IF EXISTS customer;"))
        conn.commit()
        print("✅ Old table dropped!")

    # Push updated DataFrame
    df.to_sql(
        name="customer",
        con=engine,
        if_exists="replace",
        index=False
    )
    print(f"✅ {len(df)} rows imported successfully!")

except Exception as e:
    print("❌ Import Error:", e)

# ============================================
# STEP 9 - VERIFY IN JUPYTER
# ============================================
df_verify = pd.read_sql("SELECT * FROM customer LIMIT 5", engine)
print("\n✅ MySQL Columns:")
print(df_verify.columns.tolist())
print("\n✅ Preview from MySQL:")
print(df_verify.head())

✅ Data Loaded!
Shape: (3900, 18)
✅ Columns Renamed!
['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases']
✅ Promo Code Column Dropped!
✅ Nulls Removed! Remaining rows: 3900
✅ Frequency Mapping Done!
  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365

✅ Final Column Names:
['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'purchase_frequency_days']

✅ Final Shape: (3900, 18)

✅ Preview:
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365

✅ Connected to: ('customer_behavior',)
✅ Old table dropped!
✅ 3900 rows imported successfully!

✅ MySQL Columns:
['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'purchase_frequency_days']

✅ Preview from MySQL:
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365

In [103]:
from sqlalchemy import create_engine, text

# Connect to MySQL
engine = create_engine("mysql+pymysql://root:13082003@localhost:3306/Customer_behavior")

# Drop old table
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS customer;"))
    conn.commit()
    print("✅ Old table dropped!")

# Push all changes to MySQL
df.to_sql(
    name="customer",
    con=engine,
    if_exists="replace",
    index=False
)
print(f"✅ {len(df)} rows imported with all changes!")

# Verify
df_verify = pd.read_sql("SELECT * FROM customer LIMIT 3", engine)
print("\n✅ Updated columns in MySQL:")
print(df_verify.columns.tolist())

✅ Old table dropped!
✅ 3900 rows imported with all changes!

✅ Updated columns in MySQL:
['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [130]:
print(df.columns.tolist())
print(df.shape)

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'purchase_frequency_days']
(3900, 18)

In [131]:
from sqlalchemy import create_engine, text
import pandas as pd

# ============================================
# STEP 1 - APPLY AGE GROUP CHANGE
# ============================================
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

# Convert to string for MySQL compatibility
df['age_group'] = df['age_group'].astype(str)

print("✅ Age Group Column Added!")
print(df[['age', 'age_group']].head(10))
print("\nAge Group Distribution:")
print(df['age_group'].value_counts())

# ============================================
# STEP 2 - VERIFY ALL COLUMNS
# ============================================
print("\n✅ All Columns:")
print(df.columns.tolist())

# ============================================
# STEP 3 - CONNECT TO MYSQL
# ============================================
engine = create_engine("mysql+pymysql://root:13082003@localhost:3306/Customer_behavior")

try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT DATABASE();"))
        print("\n✅ Connected to:", result.fetchone())
except Exception as e:
    print("❌ Connection Error:", e)

# ============================================
# STEP 4 - DROP OLD TABLE & PUSH TO MYSQL
# ============================================
try:
    with engine.connect() as conn:
        conn.execute(text("DROP TABLE IF EXISTS customer;"))
        conn.commit()
        print("✅ Old table dropped!")

    df.to_sql(
        name="customer",
        con=engine,
        if_exists="replace",
        index=False
    )
    print(f"✅ {len(df)} rows imported with age_group column!")

except Exception as e:
    print("❌ Import Error:", e)

# ============================================
# STEP 5 - VERIFY IN JUPYTER
# ============================================
df_verify = pd.read_sql("SELECT age, age_group FROM customer LIMIT 10", engine)
print("\n✅ Age Group in MySQL:")
print(df_verify)

✅ Age Group Column Added!
   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

Age Group Distribution:
age_group
Young Adult    1028
Middle-aged     986
Senior          944
Adult           942
Name: count, dtype: int64

✅ All Columns:
['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'purchase_frequency_days', 'age_group']

✅ Connected to: ('customer_behavior',)
✅ Old table dropped!
✅ 3900 rows imported with age_group column!

✅ Age Group in MySQL:
   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged